/*----------------------------------------------------------------------------------------------
 * Copyright 2014 Federal IT Steering Unit FITSU Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 *---------------------------------------------------------------------------------------------*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.26 at 01:23:26 PM CET 
//


package ch.admin.isb.hermes5.model.api;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.admin.isb.hermes5.model.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Model_QNAME = new QName("http://www.hermes.admin.ch/model/hermes5/v1", "model");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.admin.isb.hermes5.model.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Workproduct }
     * 
     */
    public Workproduct createWorkproduct() {
        return new Workproduct();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link WorkproductRef }
     * 
     */
    public WorkproductRef createWorkproductRef() {
        return new WorkproductRef();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link Phase }
     * 
     */
    public Phase createPhase() {
        return new Phase();
    }

    /**
     * Create an instance of {@link ModuleRef }
     * 
     */
    public ModuleRef createModuleRef() {
        return new ModuleRef();
    }

    /**
     * Create an instance of {@link TaskRef }
     * 
     */
    public TaskRef createTaskRef() {
        return new TaskRef();
    }

    /**
     * Create an instance of {@link Workproduct.Template }
     * 
     */
    public Workproduct.Template createWorkproductTemplate() {
        return new Workproduct.Template();
    }

    /**
     * Create an instance of {@link Workproduct.CollaborationRoles }
     * 
     */
    public Workproduct.CollaborationRoles createWorkproductCollaborationRoles() {
        return new Workproduct.CollaborationRoles();
    }

    /**
     * Create an instance of {@link Task.ResponsibleRole }
     * 
     */
    public Task.ResponsibleRole createTaskResponsibleRole() {
        return new Task.ResponsibleRole();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link RoleRef }
     * 
     */
    public RoleRef createRoleRef() {
        return new RoleRef();
    }

    /**
     * Create an instance of {@link Tasks }
     * 
     */
    public Tasks createTasks() {
        return new Tasks();
    }

    /**
     * Create an instance of {@link Workproducts }
     * 
     */
    public Workproducts createWorkproducts() {
        return new Workproducts();
    }

    /**
     * Create an instance of {@link Modules }
     * 
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hermes.admin.ch/model/hermes5/v1", name = "model")
    public JAXBElement<ModelType> createModel(ModelType value) {
        return new JAXBElement<ModelType>(_Model_QNAME, ModelType.class, null, value);
    }

}
