--// create table transleatable text
-- Migration SQL that makes the change goes here.

CREATE TABLE TRANSLATEABLE_TEXT (
ID BIGINT NOT NULL auto_increment,
MODEL_IDENTIFIER VARCHAR(255) NOT NULL REFERENCES EPF_MODEL (IDENTIFIER),
TEXT_IDENTIFIER VARCHAR(255)  NOT NULL,
ELEMENT_IDENTIFIER VARCHAR(255),
FILE_TYPE VARCHAR(255),
FILE_NAME VARCHAR(255),
TEXT_DE LONGTEXT,
TEXT_FR LONGTEXT,
TEXT_IT LONGTEXT,
TEXT_EN LONGTEXT,
STATUS_FR VARCHAR(255),
STATUS_IT VARCHAR(255),
STATUS_EN VARCHAR(255),
PRIMARY KEY  (`ID`));

--//@UNDO
-- SQL to undo the change goes here.


DROP TABLE TRANSLATEABLE_TEXT;