--// create document table
-- Migration SQL that makes the change goes here.
CREATE TABLE DOCUMENT (
ID BIGINT NOT NULL auto_increment,
MODEL_IDENTIFIER VARCHAR(255) NOT NULL REFERENCES EPF_MODEL (IDENTIFIER),
URL_DE VARCHAR(255) NOT NULL,
URL_FR VARCHAR(255),
URL_IT VARCHAR(255),
URL_EN VARCHAR(255),
STATUS_FR VARCHAR(255),
STATUS_IT VARCHAR(255),
STATUS_EN VARCHAR(255),
PRIMARY KEY  (`ID`));


--//@UNDO
-- SQL to undo the change goes here.
DROP TABLE DOCUMENT;

