--// add status and dates to epf model
-- Migration SQL that makes the change goes here.
ALTER TABLE EPF_MODEL ADD (
STATUS_FR VARCHAR(255) NOT NULL,
STATUS_IT VARCHAR(255) NOT NULL,
STATUS_EN VARCHAR(255) NOT NULL,
LAST_PUBLICATION DATE,
LAST_CHANGE DATE);


--//@UNDO
-- SQL to undo the change goes here.
ALTER TABLE EPF_MODEL DROP COLUMN STATUS_FR;
ALTER TABLE EPF_MODEL DROP COLUMN STATUS_IT;
ALTER TABLE EPF_MODEL DROP COLUMN STATUS_EN;
ALTER TABLE EPF_MODEL DROP COLUMN LAST_PUBLICATION;
ALTER TABLE EPF_MODEL DROP COLUMN LAST_CHANGE;
