--// change date to timestamp
-- Migration SQL that makes the change goes here.
DELETE FROM EPF_MODEL;
ALTER TABLE EPF_MODEL
MODIFY LAST_PUBLICATION TIMESTAMP;
ALTER TABLE EPF_MODEL
MODIFY LAST_CHANGE TIMESTAMP;


--//@UNDO
-- SQL to undo the change goes here.
ALTER TABLE EPF_MODEL
MODIFY LAST_PUBLICATION DATE;
ALTER TABLE EPF_MODEL
MODIFY LAST_CHANGE DATE;

